# Imagen base ligera con Python 3.11
FROM python:3.11-slim

# Instalamos las dependencias mínimas para Tkinter
RUN apt-get update && apt-get install -y \
    python3-tk \
    && rm -rf /var/lib/apt/lists/*

# Establecemos directorio de trabajo
WORKDIR /app

# Copiamos el archivo de la aplicación
COPY app.py .

# Comando para ejecutar la aplicación
CMD ["python3", "app.py"]